FROM alpine:3.13

RUN apk update \
    && apk add build-base gcc g++ cmake make zlib-dev ncurses-dev musl-dev bzip2-dev xz-dev
COPY samtools-1.9.tar.bz2 /opt
COPY minimap2-2.17.tar.bz2 /opt
RUN cd /opt \
    && tar jxvf minimap2-2.17.tar.bz2 \
    && tar jxvf samtools-1.9.tar.bz2 \
    && cd minimap2-2.17/ && make && cp minimap2 /bin/ \
    && cd ../samtools-1.9 && make && cp samtools /bin/
RUN cd /opt/ && rm -rf minimap2-2.17.tar.bz2 samtools-1.9.tar.bz2 && rm -rf /var/cache/apk/*